feat: initialize foundry repo for Swaplace+CCIP #142
blockful-io/ccip pull request #7
Opened 2024-01-17 02:10 UTC by 0xjoaovpsantos

This PR close [#142](https://github.com/blockful-io/swaplace-contracts/issues/142)

Checklist:

- [x] Removed old files in the swaplace-ccip repository
- [x] Contracts brought from swaplace-contracts to swaplace-ccip
- [x] Removed the hardhat
- [x] Installed Foundry setup
- [x] Installed openzeppelin
- [x] Config the remappings.txt with openzeppelin path

2024-01-17 18:37 UTC, 0xneves commented
Hey @0xjoaovpsantos, I'll report here the review directly because using the review feature I would have to report in a lot of files.

1- It was not part of the task to bring Swaplace contracts from swaplace-contracts, the ccip contracts were already in the specified branch requested in the issue
2- The libs are not supposed to be committed, they are just like the node_modules folder from hardhat and should be left for the user to install after cloning the repository
3- You completely deleted the core CCIP.sol contracts (🙈🤣) that were already in the feat/foundry repo, which are the ones we need.
4- You also deleted the CCIP scripts which must stay in the scripts folder to aid users understand the CCIP flux to correctly implement the tests in Solidity.

Overall I think you misunderstood the entire issue and maybe lacked knowledge about what CCIP is.
Just to summarize. Swaplace-contracts is one thing, swaplace-ccip is another different thing, just like swaplace-solana or swaplace-cairo. 
Swaplace + hardhat is the core multichain EVM contract set while swaplace + foundry is the core cross-chain EVM contract set.

Let me know if you want to try again, our deadline is Thursday. After that, this will become a hot task worthing 2x points to the first one to open the correct PR.

2024-01-17 18:38 UTC, 0xneves requested changes
Requesting for a remake based on my last comment above.

2024-01-17 18:41 UTC, 0xjoaovpsantos commented
OH NO SORRY MAN @0xneves 

I'll fix all points now!!!

2024-01-17 18:57 UTC, 0xjoaovpsantos commented
@0xneves sorry man!! I fixed the points:

[x] 1- It was not part of the task to bring Swaplace contracts from swaplace-contracts, the ccip contracts were already in the specified branch requested in the issue
[x] 2- The libs are not supposed to be committed, they are just like the node_modules folder from hardhat and should be left for the user to install after cloning the repository
[x] 3- You completely deleted the core CCIP.sol contracts (🙈🤣) that were already in the feat/foundry repo, which are the ones we need.
[x] 4- You also deleted the CCIP scripts which must stay in the scripts folder to aid users understand the CCIP flux to correctly implement the tests in Solidity.

2024-01-17 20:44 UTC, luislucena16 reviewed
in general I think you should delete the `lib` folder and bring back the `CCIP` contracts and scripts that were deleted

2024-01-17 20:44 UTC, luislucena16 commented on .gitignore
> +
add this: 
`cache_forge`

2024-01-17 20:44 UTC, luislucena16 commented on foundry.toml
maybe here you can use this:
```
# Default profile with all base configs
[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'
eth_rpc_url = 'https://mainnet.infura.io/v3/apiKey' // if we need this
fork-block-number = 18135100 // if we need this
optimizer = false
solc-version = "0.8.21"
```

2024-01-17 20:52 UTC, 0xjoaovpsantos commented
> in general I think you should delete the `lib` folder and bring back the `CCIP` contracts and scripts that were deleted

All CCIP Contracts and Scripts already are in the main branch :)

2024-01-17 21:42 UTC, luislucena16 commented
yes, my comments were late. I hadn't posted them

2024-02-09 16:59 UTC, 0xneves commented
The current folder structure is incorrect and Foundry will not compile or work properly. This issue is still blocking the creation of more tasks regarding CCIP. Please help me unstuck the opportunities!

2024-02-09 17:00 UTC, 0xneves requested changes
The current folder structure is incorrect and Foundry will not compile or work properly. This issue is still blocking the creation of more tasks regarding CCIP. Please help me unstuck the opportunities!

2024-02-12 00:54 UTC, 0xjoaovpsantos commented
Hey @0xneves how are you?
I fixed it!!! 

- [x] Changed the root of project to 'src' foler
- [x] Config remapping.txt with chainlink and oepnzeppelin packages

`forge build` in the root of project:

<img width="258" alt="image" src="https://github.com/blockful-io/swaplace-ccip/assets/31141391/61e8ddf7-88d2-49f9-8c68-569da0184347">

2024-02-16 18:12 UTC, 0xneves commented
> Hey @0xneves how are you? I fixed it!!!
> 
> * [x]  Changed the root of project to 'src' foler
> * [x]  Config remapping.txt with chainlink and oepnzeppelin packages
> 
> `forge build` in the root of project:
> 
> <img alt="image" width="258" src="https://private-user-images.githubusercontent.com/31141391/303958574-61e8ddf7-88d2-49f9-8c68-569da0184347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDU4MjksIm5iZiI6MTcwODEwNTUyOSwicGF0aCI6Ii8zMTE0MTM5MS8zMDM5NTg1NzQtNjFlOGRkZjctODhkMi00OWY5LThjNjgtNTY5ZGEwMTg0MzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE3NDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZjE3M2ExOWFlOGQxNWQ4OThhMjE3ZGUwMTdlODg4NTE1MWUwNjlkZmMzYzU1OGFmN2ExNWRiNjFlZmQ4ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcDqyVjFKLaH_OP8zwWxVbpxDUVp5eqPleRCM3N0iz8">

Perfect man!! The first foundry setups we never forget hahaha
Thank you for reorganizing the repo and sorry for the late response, we've been channeling the hadron colliders to the dApp repo 🤣

2024-02-16 18:12 UTC, merged

2024-02-16 18:13 UTC, 0xneves reviewed
Perfect, approved this PR and merged to main